/**
 * @file styles.ts
 * @description Styles shared by the AI Lab sections.
 *
 * The screen was one 1,900-line file; the sections now live beside this one and import from it, so
 * a chat bubble and a task card cannot drift into two different treatments.
 */

import { StyleSheet } from 'react-native';
import { Colors, Fonts, Radius, Type } from '../../theme/colors';

export const styles = StyleSheet.create({
  agentCardHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  agentCardFoot: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  agentMeta: { fontFamily: Fonts.mono, fontSize: 11, color: Colors.dark.textMuted },
  agentRunButton: { paddingVertical: 6, paddingHorizontal: 12 },
  scaffoldHeader: { paddingHorizontal: 16, paddingTop: 8 },
  nanoMetricRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  nanoActionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  nanoError: { color: Colors.dark.error, fontSize: 11, marginTop: 8 },
  ttsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  scaffoldTabs: { paddingHorizontal: 16 },
  container: { flex: 1, backgroundColor: Colors.dark.background },
  chatScrollContent: { padding: 16, paddingBottom: 24 },
  scrollContent: { padding: 16, paddingBottom: 24 },
  controlRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  engineSwitcher: {
    flexDirection: 'row',
    backgroundColor: Colors.dark.surfaceVariant,
    borderRadius: Radius.pill,
    padding: 3,
  },
  enginePill: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: Radius.pill,
  },
  enginePillActive: {
    backgroundColor: Colors.dark.primary,
  },
  enginePillText: {
    fontSize: 12,
    fontFamily: Fonts.sans,
    fontWeight: '600',
    color: Colors.dark.textMuted,
  },
  enginePillTextActive: {
    color: Colors.dark.onPrimary,
  },
  actionPill: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: Radius.pill,
  },
  paramsDrawer: {
    backgroundColor: Colors.dark.surface,
    padding: 14,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
    marginBottom: 14,
  },
  paramsTitle: {
    fontSize: 12,
    fontFamily: Fonts.mono,
    fontWeight: '700',
    color: Colors.dark.primary,
    marginBottom: 10,
  },
  paramLabel: {
    fontSize: 11,
    fontFamily: Fonts.sans,
    color: Colors.dark.textMuted,
    marginBottom: 6,
  },
  modelRow: { flexDirection: 'row', marginBottom: 12 },
  modelChip: {
    backgroundColor: Colors.dark.card,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
    borderRadius: Radius.pill,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
  },
  modelChipActive: {
    borderColor: Colors.dark.primary,
    backgroundColor: `${Colors.dark.primary}22`,
  },
  modelChipText: {
    fontSize: 11,
    fontFamily: Fonts.mono,
    color: Colors.dark.textMuted,
  },
  modelChipTextActive: {
    color: Colors.dark.primary,
    fontWeight: '600',
  },
  paramGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  paramItem: {
    flex: 1,
    backgroundColor: Colors.dark.card,
    padding: 10,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
  },
  paramItemLabel: {
    fontSize: 11,
    fontFamily: Fonts.mono,
    color: Colors.dark.text,
    marginBottom: 6,
  },
  paramStepper: {
    flexDirection: 'row',
    gap: 8,
  },
  stepBtn: {
    flex: 1,
    backgroundColor: Colors.dark.surfaceVariant,
    paddingVertical: 4,
    alignItems: 'center',
    borderRadius: 4,
  },
  stepBtnText: {
    color: Colors.dark.text,
    fontSize: 14,
    fontWeight: '700',
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.cardBorder,
  },
  togglePill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: Radius.pill,
    backgroundColor: Colors.dark.card,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
  },
  togglePillActive: {
    borderColor: Colors.dark.success,
    backgroundColor: `${Colors.dark.success}22`,
  },
  togglePillText: {
    fontSize: 10,
    fontFamily: Fonts.mono,
    fontWeight: '700',
    color: Colors.dark.text,
  },
  chatList: { paddingBottom: 16 },
  emptyPrompt: {
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyPromptTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.dark.text,
    marginBottom: 6,
  },
  emptyPromptSub: {
    fontSize: 13,
    color: Colors.dark.textMuted,
    textAlign: 'center',
    lineHeight: 18,
  },
  messageBubble: {
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    maxWidth: '92%',
  },
  userBubble: {
    backgroundColor: Colors.dark.primaryContainer,
    alignSelf: 'flex-end',
    borderBottomRightRadius: 2,
  },
  modelBubble: {
    backgroundColor: Colors.dark.card,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 2,
  },
  systemBubble: {
    backgroundColor: `${Colors.dark.error}18`,
    borderWidth: 1,
    borderColor: Colors.dark.error,
    alignSelf: 'stretch',
    maxWidth: '100%',
  },
  bubbleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  bubbleRole: {
    fontSize: 9,
    fontFamily: Fonts.mono,
    fontWeight: '700',
    color: Colors.dark.textMuted,
    letterSpacing: 0.5,
  },
  bubbleLatency: {
    fontSize: 9,
    fontFamily: Fonts.mono,
    color: Colors.dark.textMuted,
  },
  bubbleText: {
    color: Colors.dark.text,
    fontSize: 13,
    lineHeight: 19,
    fontFamily: Fonts.sans,
  },
  thoughtBox: {
    backgroundColor: Colors.dark.surfaceVariant,
    padding: 10,
    borderRadius: Radius.sm,
    borderLeftWidth: 3,
    borderLeftColor: Colors.dark.secondary,
    marginBottom: 10,
  },
  thoughtTitle: {
    fontSize: 9,
    fontFamily: Fonts.mono,
    fontWeight: '700',
    color: Colors.dark.secondary,
    marginBottom: 4,
  },
  thoughtText: {
    fontSize: 11,
    fontFamily: Fonts.sans,
    color: Colors.dark.textMuted,
    fontStyle: 'italic',
  },
  loadingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.dark.card,
    padding: 10,
    borderRadius: Radius.md,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
  },
  loadingBubbleText: {
    color: Colors.dark.textMuted,
    fontSize: 12,
    marginLeft: 8,
    fontFamily: Fonts.sans,
  },
  composer: {
    flexDirection: 'row',
    padding: 10,
    backgroundColor: Colors.dark.surface,
    borderTopWidth: 1,
    borderTopColor: Colors.dark.cardBorder,
    alignItems: 'center',
  },
  composerInput: {
    flex: 1,
    backgroundColor: Colors.dark.card,
    color: Colors.dark.text,
    borderRadius: Radius.pill,
    paddingHorizontal: 14,
    paddingVertical: 8,
    fontSize: 13,
    marginRight: 6,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
  },
  composerMic: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 6,
    borderRadius: Radius.pill,
  },
  composerSend: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: Radius.pill,
  },
  card: {
    backgroundColor: Colors.dark.card,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
    padding: 14,
    marginBottom: 14,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: '700',
    fontFamily: Fonts.sans,
    color: Colors.dark.text,
  },
  cardDesc: {
    fontSize: 12,
    color: Colors.dark.textMuted,
    lineHeight: 17,
    marginTop: 4,
    marginBottom: 10,
  },
  taskSelector: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  taskPill: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: Colors.dark.surfaceVariant,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
  },
  taskPillActive: {
    backgroundColor: Colors.dark.primary,
    borderColor: Colors.dark.primary,
  },
  taskPillText: {
    fontSize: 10,
    fontFamily: Fonts.mono,
    fontWeight: '700',
    color: Colors.dark.textMuted,
  },
  taskPillTextActive: {
    color: Colors.dark.onPrimary,
  },
  optionRow: { flexDirection: 'row', gap: 8, marginTop: 6 },
  optionPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: Radius.pill,
    backgroundColor: Colors.dark.surfaceVariant,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
    marginRight: 6,
  },
  optionPillActive: {
    borderColor: Colors.dark.primary,
    backgroundColor: `${Colors.dark.primary}22`,
  },
  optionPillText: {
    fontSize: 10,
    fontFamily: Fonts.mono,
    color: Colors.dark.textMuted,
  },
  optionPillTextActive: {
    color: Colors.dark.primary,
    fontWeight: '700',
  },
  textInputFull: {
    backgroundColor: Colors.dark.surfaceVariant,
    color: Colors.dark.text,
    borderRadius: Radius.sm,
    padding: 10,
    fontSize: 13,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
    marginTop: 6,
  },
  textInputArea: {
    backgroundColor: Colors.dark.surfaceVariant,
    color: Colors.dark.text,
    borderRadius: Radius.sm,
    padding: 10,
    fontSize: 13,
    minHeight: 80,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
  },
  outputResultText: {
    fontSize: 13,
    lineHeight: 20,
    color: Colors.dark.text,
    marginTop: 4,
    backgroundColor: Colors.dark.surfaceVariant,
    padding: 12,
    borderRadius: Radius.sm,
  },
  outputMetaText: {
    fontSize: 11,
    fontFamily: Fonts.mono,
    color: Colors.dark.textMuted,
    marginTop: 8,
  },
  waveformContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
  },
  listeningStatusText: {
    fontSize: 12,
    color: Colors.dark.primary,
    fontFamily: Fonts.mono,
  },
  partialStreamBox: {
    marginTop: 16,
    width: '100%',
    backgroundColor: Colors.dark.surfaceVariant,
    padding: 12,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
  },
  partialStreamLabel: {
    fontSize: 9,
    fontFamily: Fonts.mono,
    fontWeight: '700',
    color: Colors.dark.primary,
    marginBottom: 4,
  },
  partialStreamText: {
    fontSize: 14,
    color: Colors.dark.text,
    fontStyle: 'italic',
  },
  previewImage: {
    width: '100%',
    height: 200,
    borderRadius: Radius.sm,
    marginTop: 12,
  },
  loadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
  },
  loadingText: {
    color: Colors.dark.primary,
    fontSize: 12,
  },
  analysisBox: {
    marginTop: 12,
    padding: 12,
    backgroundColor: Colors.dark.surfaceVariant,
    borderRadius: Radius.sm,
  },
  analysisTitle: {
    fontSize: 11,
    fontFamily: Fonts.mono,
    fontWeight: '700',
    color: Colors.dark.primary,
  },
  analysisText: {
    fontSize: 13,
    color: Colors.dark.text,
    lineHeight: 18,
    marginTop: 4,
  },
  labelsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  labelChip: {
    backgroundColor: Colors.dark.card,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: Colors.dark.cardBorder,
  },
  labelChipText: {
    fontSize: 10,
    fontFamily: Fonts.mono,
    color: Colors.dark.primary,
  },
  alertSuccess: {
    backgroundColor: '#0F3E22',
    borderColor: Colors.dark.success,
    borderWidth: 1,
    borderRadius: Radius.sm,
    padding: 10,
    marginHorizontal: 16,
    marginBottom: 8,
  },
  alertSuccessText: { color: Colors.dark.success, fontSize: 12, fontWeight: '600' },
  alertError: {
    backgroundColor: `${Colors.dark.error}22`,
    borderColor: Colors.dark.error,
    borderWidth: 1,
    borderRadius: Radius.sm,
    padding: 10,
    marginBottom: 12,
  },
  alertErrorText: { color: Colors.dark.error, fontSize: 12 },
  errorText: { color: Colors.dark.error, fontSize: 12, marginTop: 6 },
});
